name: Terraform CI

on:
  pull_request:
  push:
    branches-ignore:
      - main

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}      
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  terraform-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var "admin_login=${{ secrets.TF_SQL_ADMIN_LOGIN }}" -var "admin_password=${{ secrets.TF_SQL_ADMIN_PASSWORD}}" -var "client_ip=${{ secrets.TF_SQL_CLIENT_IP}}"
