name: Terraform CI

on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TFE_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var "admin_login=${{ secrets.TF_SQL_ADMIN_LOGIN }}" -var "admin_password=${{ secrets.TF_SQL_ADMIN_PASSWORD}}" -var "client_ip=${{ secrets.TF_SQL_CLIENT_IP}}"
