name: Terraform CI

on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var "admin_login=${{ secrets.TF_SQL_ADMIN_LOGIN }}" -var "admin_password=${{ secrets.TF_SQL_ADMIN_PASSWORD}}" -var "client_ip=${{ secrets.TF_SQL_CLIENT_IP}}"
