name: 'Destroy Terraform Resources'

on:
  workflow_dispatch: # Manual trigger

jobs:
  destroy:
    uses: Grupo-118-Tech-Challenge-Fiap-11SOAT/terraform-template-pipeline-grupo118-fase-3/.github/workflows/terraform-template-destroy-resource.yml@main
    with:
      terraform_var_mapping: |
        {
          "admin_login": "TF_SQL_ADMIN_LOGIN",
          "admin_password": "TF_SQL_ADMIN_PASSWORD",
          "client_ip": "TF_SQL_CLIENT_IP"
        }
    secrets: inherit